#!/bin/sh -e

# Copyright (C) 2023, John Clark <inindev@gmail.com>

# kernel post-install hook: /etc/kernel/postinst.d
# script to copy the specified dtb file to /boot
# after a new kernel is package installed

version="$1"
source1="/usr/lib/linux-image-${version}/rockchip/rk3568-nanopi-r5s.dtb"
source2='/boot/rk3568-nanopi-r5s.dtb'
target="/boot/rk3568-nanopi-r5s.dtb-${version}"

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "E: dtb_cp: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

if [ -f "${source1}" ]; then
	echo "I: dtb_cp: installing ${source1} to ${target}"
	install -m 644 "${source1}" "${target}"
elif [ -f "${source2}" ]; then
	echo -n "I: dtb_cp: symlink "
	ln -sfv "$(basename "${source2}")" "${target}"
else
	echo >&2 "E: dtb_cp: neither ${source1} nor ${source2} found"
	exit 3
fi

